[Web]
port = "0.0.0.0:10082"   #服务要运行的端口

[Database]
dsn = "root:root@127.0.0.1:3306/sshman"

[Redis]
addr = "127.0.0.1:6379"
password = ""           #没有则不填

[AliSms]    #阿里云短信配置
accessid = "—"
accesskey = "-"
signname = "-"  #短信签名
template = "-"  #模板代码

[Jwt]
key = "ss_jwt_token"
